"""DuckDB conventions and the parquet-to-DuckDB rebuild helper (``hoops-1lg.1.4``).

Parquet on disk is the source of truth. The DuckDB file holds nothing that
cannot be regenerated from parquet: **views** over the parquet zones plus
**materialized** gold marts. It is therefore always safe to delete — deleting it
loses no data, and :func:`rebuild_database` reconstructs an identical database
from the same parquet. That invariant is what lets the file stay off the NAS
(:mod:`hoopstate.storage`) and out of version control.

View conventions
----------------

The database exposes one relation per logical table, named ``<zone>_<table>`` so
the zone is legible in every query. Only the zones that hold tabular parquet get
relations; ``raw`` and ``cache`` are archives, and ``oracle`` is quarantined
(the test suite may read its parquet directly, but the core model's database
never surfaces it — see the project architecture notes).

``bronze`` — one **view** per *source*, unioned across seasons
    Bronze parquet is season-partitioned: ``bronze/season=<year>/<name>.parquet``
    where ``<name>`` is a manifest dataset name such as ``nbastats_2023`` or
    ``nbastats_po_2023``. Every file for a given source shares one schema, so
    they are unioned into a single view named ``bronze_<source>`` (e.g.
    ``bronze_nbastats``). The season and the regular-season/playoffs split live
    only in the file name, never in the bronze columns, so the view adds two
    columns the parquet lacks: ``season`` (``INTEGER``, null when the name
    carries no season) and ``playoffs`` (``BOOLEAN``). A query spanning all
    ingested seasons is then ``SELECT ... FROM bronze_nbastats``, filtered by
    ``season`` / ``playoffs`` as needed.

``silver`` — one **view** per parquet file
    The canonical model (``canonical_event``, ``lineup_stint``, ``possession``,
    ``possession_chance``). Each ``silver/<table>.parquet`` becomes
    ``silver_<table>``. Read live from parquet: silver is regenerated by the
    derivation stage, and a view always reflects the current parquet.

``gold`` — one **materialized table** per parquet file
    The versioned analysis marts — the future API contract. Each
    ``gold/<mart>.parquet`` is loaded into a ``gold_<mart>`` **table**, not a
    view: gold is the served surface, and materializing decouples reads from the
    parquet layout so the contract is stable and fast. Still fully rebuildable —
    the table is ``CREATE TABLE ... AS SELECT`` from the parquet on every
    rebuild — so deleting the database and rebuilding is a no-op on results.

In-database gold marts
----------------------

Some gold marts are published as parquet (handled above); others are derived in
SQL from the silver/bronze views. The latter are passed to
:func:`rebuild_database` as ``gold_marts`` — a mapping of mart name to the
``SELECT`` that defines it — and each is materialized as a ``gold_<name>`` table
after the parquet-backed relations exist, so a mart's SQL may reference them. The
registry is empty until the possession/chance and analysis work lands; the plumbing
is here so those marts have a single, rebuildable home.

Rebuild command
---------------

``python -m hoopstate.db.rebuild`` (or ``make rebuild-db``) deletes the DuckDB
file and rebuilds it from parquet under the active storage profile. It is the one
command the acceptance criteria call for: deleting the file and running it again
produces identical query results.
"""

from __future__ import annotations

import argparse
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path

import duckdb

from hoopstate.ingest.bulk_loader import parse_dataset_name
from hoopstate.storage import StorageProfile, Zone, resolve_profile

__all__ = [
    "VIEW_ZONES",
    "GoldMarts",
    "RebuildResult",
    "Relation",
    "plan_relations",
    "rebuild_database",
]

# Zones that hold tabular parquet and therefore get relations in the database.
# ``raw``/``cache`` are archive/download bookkeeping, not tables; ``oracle`` is
# quarantined and deliberately never surfaced in the core-model database.
VIEW_ZONES: tuple[Zone, ...] = (Zone.BRONZE, Zone.SILVER, Zone.GOLD)

# A registry of in-database gold marts: mart name -> the ``SELECT`` that defines
# it. Materialized as ``gold_<name>`` tables after the parquet relations exist.
GoldMarts = Mapping[str, str]


@dataclass(frozen=True)
class Relation:
    """One relation the rebuild will create, computed before touching the database.

    ``name`` is the SQL identifier (``bronze_nbastats``, ``silver_possession``,
    ``gold_lineups``). ``materialized`` is true for a ``TABLE`` and false for a
    ``VIEW``. ``sources`` are the parquet files it reads, in the deterministic
    order they are unioned — empty for an in-database gold mart, whose definition
    is SQL rather than parquet.
    """

    name: str
    zone: Zone
    materialized: bool
    sources: tuple[Path, ...]


@dataclass(frozen=True)
class RebuildResult:
    """The outcome of a rebuild: where the database landed and what it contains."""

    db_path: Path
    relations: tuple[Relation, ...]


def _quote_identifier(name: str) -> str:
    """Quote a SQL identifier, escaping embedded double quotes."""
    escaped = name.replace('"', '""')
    return f'"{escaped}"'


def _quote_literal(value: str) -> str:
    """Quote a SQL string literal, escaping embedded single quotes."""
    escaped = value.replace("'", "''")
    return f"'{escaped}'"


def _discover_parquet(root: Path) -> list[Path]:
    """Every ``*.parquet`` under ``root`` (recursively), sorted for determinism.

    A missing zone directory yields no files rather than raising: zones are
    created lazily as their producing stage first writes to them, so a fresh
    checkout has bronze but no silver or gold yet.
    """
    if not root.exists():
        return []
    return sorted(p for p in root.rglob("*.parquet") if p.is_file())


def _bronze_relations(profile: StorageProfile) -> list[Relation]:
    """Group bronze parquet by source into one union view per source."""
    root = profile.zone(Zone.BRONZE)
    by_source: dict[str, list[Path]] = {}
    for path in _discover_parquet(root):
        source = parse_dataset_name(path.stem).source
        by_source.setdefault(source, []).append(path)
    return [
        Relation(
            name=f"bronze_{source}",
            zone=Zone.BRONZE,
            materialized=False,
            sources=tuple(paths),  # already sorted by _discover_parquet
        )
        for source, paths in sorted(by_source.items())
    ]


def _flat_zone_relations(
    profile: StorageProfile, zone: Zone, *, materialized: bool
) -> list[Relation]:
    """One relation per parquet file in a flat zone (silver, gold)."""
    return [
        Relation(
            name=f"{zone.value}_{path.stem}",
            zone=zone,
            materialized=materialized,
            sources=(path,),
        )
        for path in _discover_parquet(profile.zone(zone))
    ]


def plan_relations(profile: StorageProfile) -> list[Relation]:
    """Compute every parquet-backed relation the rebuild will create.

    Pure: it inspects the parquet on disk and returns the plan without opening a
    database. In-database gold marts (the ``gold_marts`` registry) are *not*
    included here — they have no parquet sources and are appended by
    :func:`rebuild_database` itself.
    """
    relations = _bronze_relations(profile)
    relations += _flat_zone_relations(profile, Zone.SILVER, materialized=False)
    relations += _flat_zone_relations(profile, Zone.GOLD, materialized=True)
    return relations


def _bronze_view_sql(relation: Relation) -> str:
    """A ``CREATE VIEW`` unioning a source's parquet, adding season/playoffs.

    Bronze columns carry neither season nor the playoffs split — both live only
    in the file name — so each file is selected with two literal columns and the
    files are combined with ``UNION ALL BY NAME`` (robust to column ordering).

    ``hive_partitioning=false`` is required: the parquet lives under a
    ``season=<year>`` directory, which DuckDB would otherwise auto-detect as a
    hive partition and surface as its own ``season`` column, colliding with the
    literal added here. The literal is authoritative (it also encodes the
    playoffs split, which the directory layout does not).
    """
    selects = []
    for path in relation.sources:
        parsed = parse_dataset_name(path.stem)
        season = "NULL" if parsed.season is None else str(parsed.season)
        playoffs = "TRUE" if parsed.playoffs else "FALSE"
        selects.append(
            f"SELECT *, CAST({season} AS INTEGER) AS season, "
            f"CAST({playoffs} AS BOOLEAN) AS playoffs "
            f"FROM read_parquet({_quote_literal(str(path))}, hive_partitioning=false)"
        )
    body = "\nUNION ALL BY NAME\n".join(selects)
    return f"CREATE VIEW {_quote_identifier(relation.name)} AS\n{body}"


def _flat_relation_sql(relation: Relation) -> str:
    """A ``CREATE VIEW``/``CREATE TABLE`` over a single parquet file."""
    (path,) = relation.sources
    keyword = "TABLE" if relation.materialized else "VIEW"
    # hive_partitioning=false for the same reason as bronze: never let a
    # ``key=value`` path component silently inject a column into the relation.
    select = f"SELECT * FROM read_parquet({_quote_literal(str(path))}, hive_partitioning=false)"
    return f"CREATE {keyword} {_quote_identifier(relation.name)} AS {select}"


def _relation_sql(relation: Relation) -> str:
    if relation.zone is Zone.BRONZE:
        return _bronze_view_sql(relation)
    return _flat_relation_sql(relation)


def rebuild_database(
    *,
    profile: StorageProfile | None = None,
    db_path: Path | None = None,
    gold_marts: GoldMarts | None = None,
) -> RebuildResult:
    """Rebuild the DuckDB database from parquet under the active profile.

    Deletes any existing database file (and its WAL sidecar) first, so the result
    never carries stale objects — the database is reconstructed from scratch every
    time, which is what makes deleting-and-rebuilding produce identical results.

    ``profile`` defaults to the resolved storage profile; ``db_path`` defaults to
    that profile's :meth:`~hoopstate.storage.StorageProfile.duckdb_path`, always
    on local disk. ``gold_marts`` maps a mart name to the ``SELECT`` defining it;
    each is materialized as a ``gold_<name>`` table after the parquet relations
    exist, so mart SQL may reference the bronze/silver/gold relations.
    """
    if profile is None:
        profile = resolve_profile()
    if db_path is None:
        db_path = profile.duckdb_path()
    if gold_marts is None:
        gold_marts = {}

    # Delete first: a rebuild is defined as "from scratch", not "in place".
    db_path.unlink(missing_ok=True)
    db_path.with_name(db_path.name + ".wal").unlink(missing_ok=True)
    db_path.parent.mkdir(parents=True, exist_ok=True)

    relations = plan_relations(profile)

    connection = duckdb.connect(str(db_path))
    try:
        for relation in relations:
            connection.execute(_relation_sql(relation))

        mart_relations: list[Relation] = []
        for name, select in gold_marts.items():
            identifier = _quote_identifier(f"gold_{name}")
            connection.execute(f"CREATE TABLE {identifier} AS {select}")
            mart_relations.append(
                Relation(name=f"gold_{name}", zone=Zone.GOLD, materialized=True, sources=())
            )
    finally:
        connection.close()

    return RebuildResult(db_path=db_path, relations=tuple(relations) + tuple(mart_relations))


def main(argv: list[str] | None = None) -> int:
    """CLI: ``python -m hoopstate.db.rebuild`` — rebuild the DB from parquet."""
    parser = argparse.ArgumentParser(
        description="Rebuild the DuckDB database from parquet (always safe to delete first)."
    )
    parser.parse_args(argv)

    result = rebuild_database()
    print(f"Rebuilt {result.db_path}")
    for relation in result.relations:
        kind = "table" if relation.materialized else "view"
        print(f"  {relation.name} ({kind}, {len(relation.sources)} parquet)")
    print(f"{len(result.relations)} relations")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
